import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = { children: ReactNode}

const Layout = ({ children }: Props) => {
  return <div>
    <Header />
    <main>{children}</main>
    <Footer />
    </div>
  
}

export default Layout;